name: Update datasets

on:
  workflow_dispatch:
  schedule:
    # run at 4am in the morning on every Monday.
    - cron: '0 4 * * 1'

jobs:
  update-datasets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Run gen_dataset script
      run: |
        bash gen_dataset.sh

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'Github Action'
        git config --global user.email 'action@github.com'
        git add -u
        git commit -m "Update contributors dataset"
        git push
